wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.5
batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 128
learn_rate:
  value: 0.001
n_layers:
  value: 4
optimizer:
  value: nesterov_accelerated_gradient_descent
weight_init:
  value: xavier
