wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.0005
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 128
learn_rate:
  value: 0.001
n_layers:
  value: 4
optimizer:
  value: rmsprop
weight_init:
  value: random
