wandb_version: 1

activation:
  value: relu
alpha:
  value: 0
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 32
learn_rate:
  value: 0.0001
n_layers:
  value: 3
optimizer:
  value: momentum_gradient_descent
weight_init:
  value: random
