wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.5
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 128
learn_rate:
  value: 0.001
n_layers:
  value: 5
optimizer:
  value: momentum_gradient_descent
weight_init:
  value: random
