wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0.5
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 32
learn_rate:
  value: 0.0001
n_layers:
  value: 4
optimizer:
  value: adam
weight_init:
  value: random
