wandb_version: 1

activation:
  value: relu
alpha:
  value: 0
batch_size:
  value: 32
epochs:
  value: 10
hidden_layer_size:
  value: 128
learn_rate:
  value: 0.001
n_layers:
  value: 5
optimizer:
  value: nadam
weight_init:
  value: random
