wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0
batch_size:
  value: 64
epochs:
  value: 5
hidden_layer_size:
  value: 64
learn_rate:
  value: 0.0001
n_layers:
  value: 5
optimizer:
  value: adam
weight_init:
  value: random
