wandb_version: 1

activation:
  value: relu
alpha:
  value: 0.0005
batch_size:
  value: 16
epochs:
  value: 10
hidden_layer_size:
  value: 128
learn_rate:
  value: 0.0001
n_layers:
  value: 3
optimizer:
  value: rmsprop
weight_init:
  value: xavier
