wandb_version: 1

activation:
  value: tanh
alpha:
  value: 0
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 32
learn_rate:
  value: 0.0001
n_layers:
  value: 5
optimizer:
  value: gradient_descent
weight_init:
  value: xavier
