wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      4: 3.7.3
      5: 0.10.21
      8:
      - 3
      - 5
activation:
  desc: null
  value: tanh
alpha:
  desc: null
  value: 0.0005
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
hidden_layer_size:
  desc: null
  value: 32
learn_rate:
  desc: null
  value: 0.0001
n_layers:
  desc: null
  value: 3
optimizer:
  desc: null
  value: gradient_descent
weight_init:
  desc: null
  value: random
